### ISSUE TITLE
Idea for modification

### ISSUE THREAD

**Issue by EvanCarroll** [pramsey/pgsql-postal#8]
Don't return a jsonb object. Instead, return a composite `postaladdr` type. Then provide a custom cast from `libpostal` to `jsonb`, and to [`norm_addy`](http://postgis.net/docs/Normalize_Address.html) then it would work with PostGIS Geocoding.

**Comment by pramsey** [comment]
Unfortunately we cannot cast to norm_addy without adding a dependency on postgis (and the geocoder at that). Ends up being something like the pointcloud_postgis extension, the extra bits of pointcloud that require postgis. Ugly overhead for a teeny little extension like this. 

Why the composite type? I mean, I probably considered it, but it seems like excess overhead since we have a perfectly good key/value store lying around.
